spring.application.name=ogarnijsie
# Port Standardowy dla backedu
server.port=8080

# Konfiguracja polaczenia z baza
spring.datasource.url=jdbc:mysql://localhost:3306/ogarnijsie_db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Tworzenie tabeli na podstawie kodu (zalety Springa)
spring.jpa.hibernate.ddl-auto=update

# Pokazywanie zapytan SQL w konsoli
spring.jpa.show-sql=true